FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
ENV DEBIAN_FRONTEND=noninteractive

COPY . /app

RUN chmod +x /app/docker/updater-entrypoint.sh

CMD ["/app/docker/updater-entrypoint.sh"]
